import Config

# Configure your database
config :pax_demo, PaxDemo.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "pax_demo_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :pax_demo, PaxDemoWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "BIe/RdYEM19PBKiMpt3g4POaQTcX7q03f5LLV0OrgGqE4tLMeCPPy0k5Ry4Lusjj",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:pax_demo, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:pax_demo, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# If a local copy of Pax is being used as our dependency, then set up some extra debug configuration
if Mix.Project.deps_scms()[:pax] == Mix.SCM.Path do
  pax_path = Mix.Project.deps_paths()[:pax]

  IO.puts("Using local copy of Pax from #{pax_path}")

  # Configure Phoenix.CodeReloader to reload pax as well as this application on every request, instead of just this app
  config :pax_demo, PaxDemoWeb.Endpoint, reloadable_apps: [:pax_demo, :pax]

  # Configure Phoenix.LiveReloader to Watch this app and the pax app during development and trigger reloads
  config :phoenix_live_reload, :dirs, [pax_path, "./"]

  config :pax_demo, PaxDemoWeb.Endpoint,
    live_reload: [
      patterns: [
        ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
        ~r"priv/gettext/.*(po)$",
        ~r"lib/pax_demo_web/(controllers|live|components)/.*(ex|heex)$",
        ~r"lib/pax/?.*/(controllers|live|components)/.*(ex|heex)$"
      ]
    ]

  # Pax configuration for development
  config :pax,
    validate_config_spec: true
else
  # Watch static and templates for browser reloading.
  config :pax_demo, PaxDemoWeb.Endpoint,
    live_reload: [
      patterns: [
        ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
        ~r"priv/gettext/.*(po)$",
        ~r"lib/pax_demo_web/(controllers|live|components)/.*(ex|heex)$"
      ]
    ]
end

# Enable dev routes for dashboard and mailbox
config :pax_demo, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  # debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
